@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class AssetSetter {
  + AssetSetter(GameHandler): 
  + setNPC(): void
  + setObject(): void
}
class CollisionChecker {
  + CollisionChecker(GameHandler): 
  + checkEntity(Entity, Entity[]): int
  + checkTile(Entity): void
  + checkPlayer(Entity): void
  + checkObject(Entity, boolean): int
}
class Entity {
  + Entity(GameHandler): 
  + update(): void
  + draw(Graphics2D): void
}
class EventHandler {
  + EventHandler(GameHandler): 
  + hit(int, int, String): boolean
  + checkEvent(): void
}
class GUI {
  + GUI(boolean, int, int): 
  + openWindow(): void
  + closeWindow(): void
}
class GameHandler {
  + GameHandler(): 
  + setupGame(): void
  + reSetupGame(): void
  + update(): void
  + playSE(int): void
  + startGameThread(): void
  + playMusic(int): void
  + stopMusic(): void
  + paintComponent(Graphics): void
  + run(): void
  + reStartWindow(): void
}
class ImageHandler {
  + ImageHandler(): 
  + ImageInitializer(int, String, String, String, int, int): void
}
class KeyHandler {
  + KeyHandler(): 
  + keyPressed(KeyEvent): void
  + keyReleased(KeyEvent): void
  + keyTyped(KeyEvent): void
}
class Main {
  + Main(): 
  + main(String[]): void
}
class Player {
  + Player(GameHandler, KeyHandler): 
  + draw(Graphics2D): void
  + pickUpObject(int): void
  + getPlayerImage(): void
  + interactNPC(int): void
  + setDefaultValues(): void
  + update(): void
}
class SaveCompiler {
  + SaveCompiler(): 
  + SaveReader(GameHandler, String): void
  + SaveWriter(): void
}
class Settings {
  + Settings(): 
  + uploadSettings(GameHandler): void
  + installSettings(GameHandler, boolean, int, int, int, int, boolean, float, float): void
}
class Sound {
  + Sound(): 
  + play(): void
  + loop(): void
  + stop(): void
   file: int
   volume: float
}
class SuperObject {
  + SuperObject(): 
  + draw(Graphics2D, GameHandler): void
}
class Tile {
  + Tile(): 
}
class TileManager {
  + TileManager(GameHandler, String): 
  + getTileImage(): void
  + setup(int, String, String, String, int, int, boolean): void
  + draw(Graphics2D): void
  + loadMap(String): void
}
class UI {
  + UI(GameHandler): 
  + showMessage(String): void
  + drawDialogueScreen(): void
  + draw(Graphics2D): void
  + drawSettingScreen(): void
  + getXforCenteredText(String): int
  + getYforText(String): int
  + drawPauseScreen(): void
  + drawSubWindow(int, int, int, int): void
  + drawTitleScreen(): void
}
class UtilityTool {
  + UtilityTool(): 
  + scaleImage(BufferedImage, int, int): BufferedImage
}

AssetSetter      "1" *-[#595959,plain]-> "gameH\n1" GameHandler      
CollisionChecker "1" *-[#595959,plain]-> "gameH\n1" GameHandler      
Entity           "1" *-[#595959,plain]-> "gameH\n1" GameHandler      
EventHandler     "1" *-[#595959,plain]-> "gameH\n1" GameHandler      
GUI              "1" *-[#595959,plain]-> "imageH\n1" ImageHandler     
GUI               -[#595959,dashed]->  ImageHandler     : "«create»"
GUI               -[#595959,dashed]->  KeyHandler       : "«create»"
GUI              "1" *-[#595959,plain]-> "keyH\n1" KeyHandler       
GameHandler      "1" *-[#595959,plain]-> "aSetter\n1" AssetSetter      
GameHandler       -[#595959,dashed]->  AssetSetter      : "«create»"
GameHandler       -[#595959,dashed]->  CollisionChecker : "«create»"
GameHandler      "1" *-[#595959,plain]-> "cChecker\n1" CollisionChecker 
GameHandler       -[#595959,dashed]->  Entity           : "«create»"
GameHandler      "1" *-[#595959,plain]-> "npc\n1" Entity           
GameHandler       -[#595959,dashed]->  EventHandler     : "«create»"
GameHandler      "1" *-[#595959,plain]-> "eHandler\n1" EventHandler     
GameHandler       -[#595959,dashed]->  GUI              : "«create»"
GameHandler      "1" *-[#595959,plain]-> "myGUI\n1" GUI              
GameHandler      "1" *-[#595959,plain]-> "keyH\n1" KeyHandler       
GameHandler       -[#595959,dashed]->  KeyHandler       : "«create»"
GameHandler      "1" *-[#595959,plain]-> "player\n1" Player           
GameHandler       -[#595959,dashed]->  Player           : "«create»"
GameHandler       -[#595959,dashed]->  SaveCompiler     : "«create»"
GameHandler      "1" *-[#595959,plain]-> "saveC\n1" SaveCompiler     
GameHandler      "1" *-[#595959,plain]-> "settings\n1" Settings         
GameHandler       -[#595959,dashed]->  Settings         : "«create»"
GameHandler      "1" *-[#595959,plain]-> "music\n1" Sound            
GameHandler       -[#595959,dashed]->  Sound            : "«create»"
GameHandler      "1" *-[#595959,plain]-> "obj\n1" SuperObject      
GameHandler       -[#595959,dashed]->  SuperObject      : "«create»"
GameHandler       -[#595959,dashed]->  TileManager      : "«create»"
GameHandler      "1" *-[#595959,plain]-> "tileM\n1" TileManager      
GameHandler       -[#595959,dashed]->  UI               : "«create»"
GameHandler      "1" *-[#595959,plain]-> "ui\n1" UI               
ImageHandler      -[#595959,dashed]->  UtilityTool      : "«create»"
Main              -[#595959,dashed]->  GameHandler      : "«create»"
Player            -[#000082,plain]-^  Entity           
Player            -[#595959,dashed]->  ImageHandler     : "«create»"
Player           "1" *-[#595959,plain]-> "imageH\n1" ImageHandler     
Player           "1" *-[#595959,plain]-> "keyH\n1" KeyHandler       
SaveCompiler     "1" *-[#595959,plain]-> "gameH\n1" GameHandler      
SaveCompiler     "1" *-[#595959,plain]-> "player\n1" Player           
SaveCompiler      -[#595959,dashed]->  Settings         : "«create»"
SaveCompiler     "1" *-[#595959,plain]-> "settings\n1" Settings         
Settings         "1" *-[#595959,plain]-> "gameH\n1" GameHandler      
Settings         "1" *-[#595959,plain]-> "player\n1" Player           
SuperObject       -[#595959,dashed]->  UtilityTool      : "«create»"
SuperObject      "1" *-[#595959,plain]-> "uTool\n1" UtilityTool      
TileManager      "1" *-[#595959,plain]-> "gameH\n1" GameHandler      
TileManager      "1" *-[#595959,plain]-> "imageH\n1" ImageHandler     
TileManager       -[#595959,dashed]->  ImageHandler     : "«create»"
TileManager      "1" *-[#595959,plain]-> "tile\n*" Tile             
TileManager       -[#595959,dashed]->  Tile             : "«create»"
UI               "1" *-[#595959,plain]-> "gameH\n1" GameHandler      
@enduml
